cit/urls.py
from django.urls import path
from . import views
from . import scaffolding
from base.views import TemplateHomeView

from utils import navigate

app_name='cit'


urlpatterns = [
	path('', TemplateHomeView.as_view(
		template_name = 'cit/index.html', 
		module='cit',
		page_name='Dashboard',
		page_title='CIT Module',
		parent_menu=[['CIT','cit:home']]
	), name="home"),
	
	# path('productivity/', views.get_productivity, name='productivity'),
	# path('calendar/', views.calendar_view, name='calendar'),
	# path('events-json/', views.events_json, name="events_json"),
    # path('update-event/', views.update_event, name="update_event"),

]
urlpatterns += scaffolding.ManufacturerCrudManager().get_url_patterns()
urlpatterns += scaffolding.RadioCrudManager().get_url_patterns()
urlpatterns += scaffolding.RadioLicenseCrudManager().get_url_patterns()

comment/urls.py
from django.urls import path
from .views import add_post, delete_post
from .scaffolding import PostCrudManager
from base.views import TemplateHomeView

app_name = 'comment'

urlpatterns = [
    path('add-for/<app_label>/<model_name>/<int:pk>/',add_post,name="add"),
    path('delete/<int:post_pk>/', delete_post, name="delete"),
    path('', TemplateHomeView.as_view(template_name='comment/comment_home.html'),name='home'),
]

urlpatterns += PostCrudManager().get_url_patterns()



xys/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views import i18n
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/jsi18n/', i18n.JavaScriptCatalog.as_view(), name='jsi18n'),
    path("select2/", include("django_select2.urls")),

    path('', include('base.urls')),
    path('document/', include('document.urls')),
    path('comment/', include('comment.urls')),
    # path('project/', include('project.urls')),
    # path('cit/', include('cit.urls')),
    # path('inventory/', include('inventory.urls')),
]

@login_required
def protected_serve(request, path, document_root=None, show_indexes=False):
    return serve(request, path, document_root, show_indexes)


# This will serve the static and media files even when Debug Mode is False
if settings.DEBUG is False:
    urlpatterns += [
        re_path(
            r'^%s(?P<path>.*)$' % settings.STATIC_URL[1:],
            protected_serve,
            {'document_root': settings.STATIC_ROOT}
        ),
    ]
    urlpatterns += [
        re_path(
            r'^%s(?P<path>.*)$' % settings.MEDIA_URL[1:],
            protected_serve,
            {'document_root': settings.MEDIA_ROOT}
        ),
    ]


comment/models.py
from django.contrib.auth.models import User
from django.db import models
from django.conf import settings
from django.utils.text import Truncator
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.utils.translation import gettext_lazy as _


class PostManager(models.Manager):
    def posts_for_object(self, obj):
        object_type = ContentType.objects.get_for_model(obj)
        return self.filter(content_type__pk=object_type.id, object_id=obj.pk)


class Post(models.Model):
    message = models.TextField(max_length=4000)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    topic = GenericForeignKey('content_type', 'object_id')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(null=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="created_posts",
        verbose_name=_('post_creator'),
        on_delete=models.CASCADE,
    )
    updated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="+",
        verbose_name=_('post_updator'),
        on_delete=models.CASCADE,
    )

    objects = PostManager()

    class Meta:
        verbose_name = _("post")
        verbose_name_plural = _("posts")
        ordering = ['created_at']
        permissions = (
            ('delete_foreign_posts', _('Can delete foreign posts')),
        )

    def __str__(self):
        truncated_message = Truncator(self.message)
        return truncated_message.chars(30)

comment/forms.py
from django import forms
from django.contrib.contenttypes.models import ContentType
from crispy_forms.layout import Field, Column
from base.forms import Helper, SELECTFILTER_CSS
# from django.utils.translation import ugettext_lazy as _

from .models import Post


class PostForm(forms.ModelForm):
    message = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = Post
        fields = ('message',)

    def __init__(self, *args, **kwargs):
        self.helper = Helper()
        self.helper.field_layout(
            Column(Field('message'),css_class="col-12")
        )
        super(PostForm, self).__init__(*args, **kwargs)

    def save(self, request, obj, *args, **kwargs):
        self.instance.created_by = request.user
        self.instance.updated_by = request.user
        self.instance.content_type = ContentType.objects.get_for_model(obj)
        self.instance.object_id = obj.pk
        super(PostForm, self).save(*args, **kwargs)

comment/views.py
import os

from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.template.context import RequestContext
from django.urls import reverse
from django.utils.translation import gettext
from django.views.decorators.http import require_POST

from .forms import PostForm
from .models import Post


def add_url_for_obj(obj):
    return reverse(
        'comment:add',
        kwargs={
            'app_label': obj._meta.app_label,
            'model_name': obj._meta.model_name,
            'pk': obj.pk,
        },
    )


@require_POST
@login_required
def add_post(
    request,
    app_label,
    model_name,
    pk,
    template_name='comment/add_form.html',
    extra_context=None,
):
    next_ = request.POST.get('next', '/')

    if not request.user.has_perm('comment.add_post'):
        return HttpResponseRedirect(next_)

    model = apps.get_model(app_label, model_name)
    obj = get_object_or_404(model, pk=pk)
    form = PostForm(request.POST, request.FILES)
    success_message = 'Your comment was successfully posted.'

    if form.is_valid():
        form.save(request, obj)
        messages.success(request, gettext(success_message))
        return HttpResponseRedirect(next_)

    template_context = {
        'form': form,
        'form_url': add_url_for_obj(obj),
        'next': next_,
    }
    template_context.update(extra_context or {})

    return render(
        template_name, template_context, RequestContext(request)
    )


@login_required
def delete_post(request, post_pk):
    g = get_object_or_404(Post, pk=post_pk)
    success_message = 'Your comment was successfully deleted.'

    if (
        request.user.has_perm('comment.delete_post') and
        request.user == g.created_by
    ) or request.user.has_perm('comment.delete_foreign_posts'):
        g.delete()
        messages.success(request, gettext(success_message))
    next_ = request.GET.get('next') or '/'
    return HttpResponseRedirect(next_)

comment/templates/comment/add_form.html
{% load i18n %}

{% if form %}
<form class="form-inline" method="post" action="{{ form_url }}">
  {% csrf_token %}
  <input type="hidden" name="next" value="{{ next }}"/>
  <textarea name="message" rows="4" cols="150" style="box-sizing: border-box;
  max-width: 100%;" required id="id_message" 
    placeholder="Type your comments here"></textarea>
    <div class="text-center">
  <button class="btn btn-outline-primary btn-sm" type="submit" value="{% trans "Add post" %}">
    <i class="bi bi-upload"></i> Post Comment
  </button>
</div>
</form>


{% endif %}

comment/templates/comment/delete_link.html
{% load i18n %}
{% if delete_url %}
	{% comment %}
	<a class="delete-document" href="{{ delete_url }}?next={{ next }}">
		{% trans "Delete this document" %}
	</a>
    <a class="dropdown-item" href="#" 
    data-toggle="modal" data-target="#delete{{ modal_pk }}">
    <i class="bi bi-trash fa-fw"></i>
  </a>
	{% endcomment %}


  <div class="btn-group" role="group" aria-label="Left group">
    <button type="button" class="btn btn-outline-danger btn-sm" data-bs-toggle="modal" data-bs-target="#delete-comment">
    <i class="bi bi-trash"></i> Delete</button>
  </div>

{% endif %}

<!--DELETE MODAL-->
<div class="modal fade" id="delete-comment" tabindex="-1">
<div class="modal-dialog">
<div class="modal-content">
  <div class="modal-header">
    <h5 class="modal-title">Delete Comment</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
  </div>
  <div class="modal-body">
    Do you want to delete this comment?
  </div>
      <div class="modal-footer">
        <button class="btn btn-outline-success btn-sm" onclick='location.href="{{ delete_url }}?next={{ next }}"'>
        <i class="bi bi-trash"></i> Yes, delete</button>
        <button class="btn btn-outline-danger btn-sm" type="button" data-dismiss="modal">
        <i class='bi bi-x-lg'></i> Cancel</button>
      </div>
  </div>
</div>
</div>
</div>