cit/urls.py
from django.urls import path
from . import views
from . import scaffolding
from base.views import TemplateHomeView

from utils import navigate

app_name='cit'


urlpatterns = [
	path('', TemplateHomeView.as_view(
		template_name = 'cit/index.html', 
		module='cit',
		page_name='Dashboard',
		page_title='CIT Module',
		parent_menu=[['CIT','cit:home']]
	), name="home"),
	
	# path('productivity/', views.get_productivity, name='productivity'),
	# path('calendar/', views.calendar_view, name='calendar'),
	# path('events-json/', views.events_json, name="events_json"),
    # path('update-event/', views.update_event, name="update_event"),

]
urlpatterns += scaffolding.ManufacturerCrudManager().get_url_patterns()
urlpatterns += scaffolding.RadioCrudManager().get_url_patterns()
urlpatterns += scaffolding.RadioLicenseCrudManager().get_url_patterns()

project/urls.py
# from django.contrib import admin
from django.urls import path
from . import views
# from base.views import get_obj_list
# from scrum.models import Work
# from base.views import BaseView
# from .models import DailyWork
from . import scaffolding
from base.views import TemplateHomeView

from utils import navigate

app_name='project'


urlpatterns = [
	path('', TemplateHomeView.as_view(
		template_name = 'project/index.html', 
		module='project',
		page_name='Dashboard',
		page_title='Project Module',
		parent_menu=[['Project','project:home']]
	), name="home"),
	
	path('productivity/', views.get_productivity, name='productivity'),
	path('calendar/', views.calendar_view, name='calendar'),
	path('events-json/', views.events_json, name="events_json"),
    path('update-event/', views.update_event, name="update_event"),

]
urlpatterns += scaffolding.SiteCrudManager().get_url_patterns()
urlpatterns += scaffolding.BudgetItemCrudManager().get_url_patterns()
urlpatterns += scaffolding.ActivityCrudManager().get_url_patterns()
urlpatterns += scaffolding.ProjCategoryCrudManager().get_url_patterns()
urlpatterns += scaffolding.TaskCrudManager().get_url_patterns()
urlpatterns += scaffolding.WorkCrudManager().get_url_patterns()
urlpatterns += scaffolding.UserWorkDateCrudManager().get_url_patterns()
urlpatterns += scaffolding.DailyWorkCrudManager().get_url_patterns()
urlpatterns += scaffolding.TaskChildCrudManager().get_url_patterns()
urlpatterns += scaffolding.BudgetItemChildCrudManager().get_url_patterns()
urlpatterns += scaffolding.ActivityChildCrudManager().get_url_patterns()
urlpatterns += scaffolding.DailyWorkChildCrudManager().get_url_patterns()


xys/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views import i18n
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/jsi18n/', i18n.JavaScriptCatalog.as_view(), name='jsi18n'),
    path("select2/", include("django_select2.urls")),

    path('', include('base.urls')),
    path('document/', include('document.urls')),
    path('comment/', include('comment.urls')),
    # path('project/', include('project.urls')),
    # path('cit/', include('cit.urls')),
    # path('inventory/', include('inventory.urls')),
]

@login_required
def protected_serve(request, path, document_root=None, show_indexes=False):
    return serve(request, path, document_root, show_indexes)


# This will serve the static and media files even when Debug Mode is False
if settings.DEBUG is False:
    urlpatterns += [
        re_path(
            r'^%s(?P<path>.*)$' % settings.STATIC_URL[1:],
            protected_serve,
            {'document_root': settings.STATIC_ROOT}
        ),
    ]
    urlpatterns += [
        re_path(
            r'^%s(?P<path>.*)$' % settings.MEDIA_URL[1:],
            protected_serve,
            {'document_root': settings.MEDIA_ROOT}
        ),
    ]


project/views.py
from datetime import datetime, timedelta
from django.db.models import Q
from django.http import JsonResponse, HttpResponse
from django.utils.formats import number_format
from django.urls import reverse
from django.shortcuts import render
from .models import Activity
from base.models import UserMenuOrder
import json


def get_productivity(request):
    timeframe = request.GET.get("timeframe", "this_month")

    data = {
        "this_month": request.user.project_dashboard.get_productivity if request.user.is_authenticated else 0,
        "this_year": request.user.project_dashboard.get_productivity if request.user.is_authenticated else 0,
        "all_time": request.user.project_dashboard.get_productivity if request.user.is_authenticated else 0
    }

    formatted_value = number_format(data.get(timeframe, 0), decimal_pos=2, use_l10n=True)
    return HttpResponse(f"<h6>{formatted_value}%</h6>")


def get_efficiency(request):
    timeframe = request.GET.get("timeframe", "this_month")

    data = {
        "this_month": request.user.project_dashboard.get_productivity if request.user.is_authenticated else 0,
        "this_year": request.user.project_dashboard.get_productivity if request.user.is_authenticated else 0,
        "all_time": request.user.project_dashboard.get_productivity if request.user.is_authenticated else 0
    }

    formatted_value = number_format(data.get(timeframe, 0), decimal_pos=2, use_l10n=True)
    return HttpResponse(f"<h6>{formatted_value}%</h6>")


def get_proficiency(request):
    timeframe = request.GET.get("timeframe", "this_month")

    data = {
        "this_month": request.user.project_dashboard.get_productivity if request.user.is_authenticated else 0,
        "this_year": request.user.project_dashboard.get_productivity if request.user.is_authenticated else 0,
        "all_time": request.user.project_dashboard.get_productivity if request.user.is_authenticated else 0
    }

    formatted_value = number_format(data.get(timeframe, 0), decimal_pos=2, use_l10n=True)
    return HttpResponse(f"<h6>{formatted_value}%</h6>")

def calendar_view(request):
    activities = Activity.objects.filter(Q(followers=request.user) | Q(leader=request.user)).distinct()
    context = {
        'activities': activities,
        'user_menus': UserMenuOrder.objects.my_module_menus(
            module= 'project', 
            user=request.user) or None,
        'module': 'project',
        'model':  'Activity',
        'page_name': 'Calendar',
        'page_title': 'Activity Calendar',
        'parent_menu': [['Project','project:home'], ['Activity','project:activity-list']]
    }
    return render(request, 'project/editable-calendar.html', context)


def events_json(request):
    user = request.user
    events = Activity.objects.filter(Q(followers=request.user) | Q(leader=request.user)).distinct()
    event_list = [{
        "id": event.id,
        "title": event.name,
        "start": event.start_date.strftime("%Y-%m-%d"),
        "end": event.next_day_end.strftime("%Y-%m-%d") if event.end_date else None,
        "url": reverse("project:activity-detail", kwargs={"pk": event.id}),
        "color": event.color,
        "editable": event.leader.username == user.username
    } for event in events]
    return JsonResponse(event_list, safe=False)


def update_event(request):
    if request.method == "POST":
        data = json.loads(request.body)

        # Convert timestamp to valid YYYY-MM-DD format
        start_date = datetime.strptime(data["start"], "%Y-%m-%dT%H:%M:%S.%fZ").date()
        end_date = datetime.strptime(data["end"], "%Y-%m-%dT%H:%M:%S.%fZ").date() if data.get("end") else None

        if start_date:
            start_date += timedelta(days=1)

        event = Activity.objects.get(id=data["id"])
        event.start_date = start_date
        event.end_date = end_date
        event.save()

        return JsonResponse({"status": "success"})

project/templates/project/calendar.html
{% extends 'base.html' %}

{% block extra_css %}
    {% comment %}
    <link href="https://cdn.jsdelivr.net/npm/fullcalendar@6.1.8/index.global.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/fullcalendar@6.1.8/index.global.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@fullcalendar/list@6.1.8/index.global.min.js"></script>
    {% endcomment %} 
    
    <script src='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.17/index.global.min.js'></script>
    <script src='https://cdn.jsdelivr.net/npm/@fullcalendar/bootstrap5@6.1.17/index.global.min.js'></script>

    
    <style>
        .view-buttons {
            text-align: center;
            margin-bottom: 10px;
        }
    </style>

    <script>
      document.addEventListener('DOMContentLoaded', function() {
        const calendarEl = document.getElementById('calendar')
        const calendar = new FullCalendar.Calendar(calendarEl, {
            themeSystem: 'bootstrap5',
            initialView: 'dayGridMonth',
            headerToolbar: {
                left: 'prev,next today',
                center: 'title',
                right: 'dayGridMonth,listWeek'
            },
            footerToolbar: {
                center: 'openLinkButton'
            },
            customButtons: {
                openLinkButton: {
                    text: 'Add New Activity',
                    buttonClass: 'btn btn-outline-primary',
                    click: function() {
                        window.location.href = "{% url 'project:activity-create' %}";
                        // window.open("{% url 'project:activity-create' %}");

                    }
                }
            },
            contentHeight: 'auto',
            handleWindowResize: true,
            windowResizeDelay: 150,
            events: [
                {% for event in activities %}
                {
                    title: "{{ event.name }}",
                    start: "{{ event.start_date|date:'c' }}",
                    end: "{{ event.next_day_end|date:'c' }}",
                    url: "{% url 'project:activity-detail' event.id %}",
                    color: "{{ event.color }}"
                },
                {% endfor %}
            ]
        })
        calendar.render()

        window.switchView = function(viewType) {
                calendar.changeView(viewType);
        };

      })

    </script>
{% endblock %}

{% block content %}
    <div id='calendar'></div>
{% endblock %}

project/templates/project/editable-calendar.html
{% extends 'base.html' %}

{% block extra_css %}
    {% comment %}
    <link href="https://cdn.jsdelivr.net/npm/fullcalendar@6.1.8/index.global.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/fullcalendar@6.1.8/index.global.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@fullcalendar/list@6.1.8/index.global.min.js"></script>
    {% endcomment %} 
    
    <script src='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.17/index.global.min.js'></script>
    <script src='https://cdn.jsdelivr.net/npm/@fullcalendar/bootstrap5@6.1.17/index.global.min.js'></script>

    
    <style nonce="__CSP_NONCE__">
        .view-buttons {
            text-align: center;
            margin-bottom: 10px;
        }
    </style>

    <script nonce="__CSP_NONCE__">
      document.addEventListener('DOMContentLoaded', function() {
        const calendarEl = document.getElementById('calendar')
        const calendar = new FullCalendar.Calendar(calendarEl, {
            themeSystem: 'bootstrap5',
            initialView: 'dayGridMonth',
            editable: true,
            eventResizableFromStart: true,
            eventDrop: function(info) { updateEvent(info.event); },
            eventResize: function(info) { updateEvent(info.event); },
            headerToolbar: {
                left: 'prev,next today',
                center: 'title',
                right: 'dayGridMonth,listWeek'
            },
            footerToolbar: {
                center: 'openLinkButton'
            },
            customButtons: {
                openLinkButton: {
                    text: 'Add New Activity',
                    buttonClass: 'btn btn-outline-primary',
                    click: function() {
                        window.location.href = "{% url 'project:activity-create' %}";
                        // window.open("{% url 'project:activity-create' %}");
                    }
                }
            },
            contentHeight: 'auto',
            handleWindowResize: true,
            windowResizeDelay: 150,
            events: "{% url 'project:events_json' %}",
        })
        calendar.render()

        window.switchView = function(viewType) {
                calendar.changeView(viewType);
        };

        function getCSRFToken() {
            return document.querySelector('[name=csrfmiddlewaretoken]').value;
        }

        function updateEvent(event) {
            fetch("/project/update-event/", {
                method: "POST",
                headers: { 
                    "Content-Type": "application/json",
                    "X-CSRFToken": getCSRFToken() 
                },
                body: JSON.stringify({
                    id: event.id,
                    start: event.start.toISOString(),
                    end: event.end ? event.end.toISOString() : null
                })
            });
        }
      })

    </script>
{% endblock %}

{% block content %}
    <div id='calendar'></div>
    <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
{% endblock %}

project/templates/project/index.html
{% extends 'base.html' %}
{% load humanize %}
{% load custom_tags %}

{% block content %}
<section class="section dashboard">
<div class="row">

<!-- Productvity Card -->
<div class="col-lg-4 col-md-6">
<div class="card info-card revenue-card">

  {% comment %}
  <div class="filter">
    <a class="icon" href="#" data-bs-toggle="dropdown"><i class="bi bi-three-dots"></i></a>
    <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
      <li class="dropdown-header text-start">
        <h6>Filter</h6>
      </li>
    <li><a class="dropdown-item"  
        hx-get="{% url 'project:productivity' %}?timeframe=this_month"  
        hx-target="#productivity"  
        hx-swap="innerHTML"
        hx-on::after-request="document.getElementById('timeframe-label').innerText=' | This Month' ;">
        This Month</a></li>
    <li><a class="dropdown-item"  
        hx-get="{% url 'project:productivity' %}?timeframe=this_year"  
        hx-target="#productivity"  
        hx-swap="innerHTML"
        hx-on::after-request="document.getElementById('timeframe-label').innerText=' | This Year' ;">
        This Year</a></li>
   <li><a class="dropdown-item"
        hx-get="{% url 'project:productivity' %}?timeframe=all_time"
        hx-target="#productivity"
        hx-swap="innerHTML"
        hx-on::after-request="document.getElementById('timeframe-label').innerText=' | All Time' ;">
        All Time</a></li>
    </ul>
  </div>
  {% endcomment %}

  <div class="card-body">
  <h5 class="card-title">Productivity<span id="timeframe-label"> | This Month</span></h5>
  <div class="d-flex align-items-center">
    <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
      <a href="{% url 'home' %}"><i class="bi bi-speedometer2"></i></a>
    </div>
    <div class="ps-3">
      {% comment %}
      <div id="productivity"
        hx-get="{% url 'project:productivity' %}?timeframe=this_month"
        hx-trigger="load"
        hx-swap="innerHTML">
        Loading ...
      </div>
      {% endcomment %}
      <h6>{{ user.project_dashboard.get_productivity|floatformat:2|intcomma }}%</h6>
      <span class="text-muted small pt-2 ps-1">Work Hrs / Sched & OT Hrs</span>
    </div>
  </div>
  </div>

</div>
</div><!-- End Productivity Card -->

<!-- Efficiency Card -->
<div class="col-lg-4 col-md-6">
<div class="card info-card revenue-card">

  <div class="card-body">
  <h5 class="card-title">Efficiency<span> | this month</span></h5>
  <div class="d-flex align-items-center">
    <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
      <a href="{% url 'home' %}"><i class="bi bi-graph-up"></i></a>
    </div>
    <div class="ps-3">
      <h6>{{ efficiency|floatformat:2|intcomma }}</h6>
      <h6>{{ user.project_dashboard.get_efficiency|floatformat:2|intcomma }}%</h6>
      <span class="text-muted small pt-2 ps-1">Benchmark Hrs / Work Hrs</span>
    </div>
  </div>
  </div>

</div>
</div><!-- End Efficiency Card -->

<!-- Proficiency Card -->
<div class="col-lg-4 col-md-6">
<div class="card info-card revenue-card">

  <div class="card-body">
  <h5 class="card-title">Proficiency<span> | this month</span></h5>
  <div class="d-flex align-items-center">
    <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
      <a href="{% url 'home' %}"><i class="bi bi-award"></i></a>
    </div>
    <div class="ps-3">
      <h6>{{ user.project_dashboard.get_proficiency|floatformat:2|intcomma }}%</h6>
      <span class="text-muted small pt-2 ps-1"> Productivity x Efficiency %</span>
    </div>
  </div>
  </div>

</div>
</div><!-- End Proficiency Card -->

<!-- Left side columns -->
<div class="col-lg-8">
<div class="row">

<!-- Activity Card-->
<div class="col-12">
<div class="card">
  <div class="card-body">
  <h5 class="card-title">List of followed Activities</h5>
  <div class="table-responsive">
    <table class="table datatable table-striped table-sm">
    <thead>
      <tr>
        <th>Code</th>
        <th>Name</th>
        <th>Site</th>
        <th>Start Date</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
    {% for activity in user.activity_followers.all %}
    <tr>
    <td><a href="{% url 'project:activity-detail' activity.id %}">{{ activity.code }}</a></td>
    <td>{{ activity.name }}</td>
    <td>{{ activity.site.code }}</td>
    <td>{{ activity.start_date }}</td>
    <td>Open</td>
    </tr>
    {% endfor %}
    </tbody>
  </table>
  </div>
  </div>
</div>
</div><!-- End Activity Card -->

<!-- Task Card -->
<div class="col-12">
<div class="card info-card customers-card">
  <div class="card-body">
  <h5 class="card-title">List of followed Tasks</h5>
  <div class="table-responsive">
    <table class="table datatable table-striped table-sm">
    <thead>
      <tr>
        <th>Code</th>
        <th>Name</th>
        <th>Start Date</th>
        <th>Leader</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
    {% for task in user.task_followers.all %}
    <tr>
    <td><a href="{% url 'project:task-detail' task.id %}">{{ task.code }}</a></td>
    <td>{{ task.name }}</td>
    <td>{{ task.start_date }}</td>
    <td>{{ task.leader }}</td>
    <td>Open</td>
    </tr>
    {% endfor %}
    </tbody>
  </table>
  </div>
  </div>
</div>
</div><!-- End Task Card -->

</div>
</div><!-- End Left Side Column -->

<!-- Right Side Column -->
<div class="col-lg-4">
<div class="row">

  <div class="card">
    <div class="card-body">
    <h5 class="card-title">Timekeeper Log<span> | this month</span></h5>

    <table class="table">
      <thead>
        <tr>
          <th scope="col">Record</th>
          <th scope="col">Hours</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th scope="row"><i class="bi bi-clock"></i> Schedule</th>
          <td>{{ user.project_dashboard.get_schedule|floatformat:2 }} Hrs</td>
          <td>{% if top_schedule %} <i class='bi bi-trophy'> {% endif %}</td>
        </tr>
        <tr>
          <th scope="row"><i class="bi bi-moon-stars"></i> Overtime</th>
          <td>{{ user.project_dashboard.get_overtime|floatformat:2 }} Hrs</td>
          <td>{% if top_overtime %} <i class='bi bi-trophy'> {% endif %}</td>
        </tr>
        <tr>
          <th scope="row"><i class="bi bi-house-exclamation"></i> Off Duty</th>
          <td>{{ user.project_dashboard.get_offduty|floatformat:2 }} Hrs</td>
          <td>{% if top_offduty %} <i class='bi bi-trophy'> {% endif %}</td>
        </tr>          
        <tr>
          <th scope="row"><i class="bi bi-wrench"></i> Work</th>
          <td>{{ user.project_dashboard.get_work|floatformat:2 }} Hrs</td>
          <td>{% if top_work %} <i class='bi bi-trophy'> {% endif %}</td>
        </tr>
        <tr>
          <th scope="row"><i class="bi bi-cpu"></i> Benchmark</th>
          <td>{{ user.project_dashboard.get_benchmark|floatformat:2 }} Hrs</td>
          <td>{% if top_benchmark %} <i class='bi bi-trophy'> {% endif %}</td>
        </tr>
        <tr>
          <th scope="row"><i class="bi bi-airplane"></i> Travel</th>
          <td>{{ user.project_dashboard.get_travel|floatformat:2 }} Hrs</td>
          <td>{% if top_travel %} <i class='bi bi-trophy'> {% endif %}</td>
        </tr> 
        <tr>
          <th scope="row"><i class="bi bi-suitcase"></i> Leave</th>
          <td>{{ user.project_dashboard.get_leave|floatformat:2 }} Hrs</td>
          <td>{% if top_leave %} <i class='bi bi-trophy'> {% endif %}</td>
        </tr> 
      </tbody>
    </table>
    </div>
  </div>

<!-- Budget Report -->
  <div class="card">
    <div class="card-body pb-0">
      <h5 class="card-title">Category Breakdown<span>| All Time</span></h5>
      <div id="budgetChart" style="min-height: 400px;" class="echart"></div>
    </div>
  </div><!-- End Budget Report -->

</div>
</div><!-- End Right Side Column -->

</div>
</section>

{% endblock %}
{% block extra_js %}
  <script src="https://unpkg.com/htmx.org@2.0.4" 
  integrity="sha384-HGfztofotfshcF7+8n44JQL2oJmowVChPTg48S+jvZoztPfvwD79OC/LTtG6dMp+" 
  crossorigin="anonymous"></script>
  <script src="https://unpkg.com/htmx.org@2.0.4/dist/htmx.js" 
  integrity="sha384-oeUn82QNXPuVkGCkcrInrS1twIxKhkZiFfr2TdiuObZ3n3yIeMiqcRzkIcguaof1" 
  crossorigin="anonymous"></script>

  <script src="https://code.jquery.com/jquery-3.6.1.min.js" 
    integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ="  
  crossorigin="anonymous"></script>
  {% include 'project/chart.js' %}
  {% include 'js/table-responsive.js' %}
{% endblock %}