cit/urls.py
from django.urls import path
from . import views
from . import scaffolding
from base.views import TemplateHomeView

from utils import navigate

app_name='cit'


urlpatterns = [
	path('', TemplateHomeView.as_view(
		template_name = 'cit/index.html', 
		module='cit',
		page_name='Dashboard',
		page_title='CIT Module',
		parent_menu=[['CIT','cit:home']]
	), name="home"),
	
	# path('productivity/', views.get_productivity, name='productivity'),
	# path('calendar/', views.calendar_view, name='calendar'),
	# path('events-json/', views.events_json, name="events_json"),
    # path('update-event/', views.update_event, name="update_event"),

]
urlpatterns += scaffolding.ManufacturerCrudManager().get_url_patterns()
urlpatterns += scaffolding.RadioCrudManager().get_url_patterns()
urlpatterns += scaffolding.RadioLicenseCrudManager().get_url_patterns()

xys/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views import i18n
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/jsi18n/', i18n.JavaScriptCatalog.as_view(), name='jsi18n'),
    path("select2/", include("django_select2.urls")),

    path('', include('base.urls')),
    path('document/', include('document.urls')),
    path('comment/', include('comment.urls')),
    # path('project/', include('project.urls')),
    # path('cit/', include('cit.urls')),
    # path('inventory/', include('inventory.urls')),
]

@login_required
def protected_serve(request, path, document_root=None, show_indexes=False):
    return serve(request, path, document_root, show_indexes)


# This will serve the static and media files even when Debug Mode is False
if settings.DEBUG is False:
    urlpatterns += [
        re_path(
            r'^%s(?P<path>.*)$' % settings.STATIC_URL[1:],
            protected_serve,
            {'document_root': settings.STATIC_ROOT}
        ),
    ]
    urlpatterns += [
        re_path(
            r'^%s(?P<path>.*)$' % settings.MEDIA_URL[1:],
            protected_serve,
            {'document_root': settings.MEDIA_ROOT}
        ),
    ]


base/models.py
from django.contrib.auth.models import User, Group
from django.db import models
# from django.db.models import F, Count, Q
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from .abstract import GetOrNoneManager, TemplateModel
from django_currentuser.middleware import get_current_user, get_current_authenticated_user


def image_upload(instance, filename):
    """Stores the document in a "per module/appname/primary key" folder"""
    return 'img/{app_label}/{model_name}/{pk}/{filename}'.format(
        app_label=instance._meta.app_label,
        model_name=instance._meta.model_name,
        pk=instance.pk,
        filename=filename,
    )

def get_user_menus(user):
    if user.is_superuser:
        return Menu.objects.all()
    direct_menus = list(user.profile.menu.all())
    group_menus = list(Menu.objects.filter(
        groups__in=GroupProfile.objects.filter(
            group__in=user.groups.all())))
    combined = {menu.id: menu for menu in direct_menus + group_menus }
    sorted_menus = sorted(combined.values(), key=lambda m: m.code.lower())
    return sorted_menus

class Menu(TemplateModel):
    MENU_TYPE = (
         ('Module', 'Module'),
         ('Parent', 'Parent'),
         ('Menu', 'Menu'),
         ('Label', 'Label'),
    )
    code = models.CharField(max_length=8, blank=True, null=True)
    module = models.CharField(max_length=60, blank=True, null=True)
    menu_type = models.CharField(max_length=10, default="Module", choices=MENU_TYPE)
    name = models.CharField(max_length=60, blank=True, null=True)
    url_name = models.CharField(max_length=60, blank=True, null=True)
    icon_class = models.CharField(max_length=60, blank=True, null=True)

    class Meta:
        ordering = ['code']

    def __str__(self):
        if self.module:
            return self.code + ' - ' + self.name + ' - ' + self.menu_type
        else:
            return self.name + '_' + self.menu_type

    def get_absolute_url(self):
        return reverse('menu-detail',kwargs={'pk': self.id})

    def save(self, *args, **kwargs):
        if not self.code:
            self.code = 'ZZZZ-999'
        super().save(*args, **kwargs)

class UserProfile(TemplateModel):
    user = models.OneToOneField(
        User, 
        on_delete=models.CASCADE,
        primary_key=True,
        related_name='profile',
    )
    about = models.TextField(default="", blank=True)
    company = models.CharField(max_length=60, blank=True, null=True)
    job = models.CharField(max_length=60, blank=True, null=True)
    country = models.CharField(max_length=60, blank=True, null=True)
    address = models.CharField(max_length=60, blank=True, null=True)
    phone = models.CharField(max_length=60, blank=True, null=True)
    image_file = models.ImageField(
        _('image'), upload_to=image_upload, height_field='image_height', width_field='image_width', blank=True, null=True
    )
    image_width = models.IntegerField(blank=True, null=True)
    image_height = models.IntegerField(blank=True, null=True)
    twitter = models.CharField(max_length=60, blank=True, null=True)
    facebook = models.CharField(max_length=60, blank=True, null=True)
    instagram = models.CharField(max_length=60, blank=True, null=True)
    linkedin = models.CharField(max_length=60, blank=True, null=True)
    menu = models.ManyToManyField(
        Menu,
        blank=True,
        symmetrical=False,
        related_name='users'
    )

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name = 'User Profile'

    @property
    def get_full_name(self):
        return self.user.last_name + ',' + self.user.first_name

    def get_absolute_url(self):
        return reverse('userprofile-detail',kwargs={'pk': self.pk})

class Department(TemplateModel):
    code = models.CharField(max_length=60, blank=True, null=True)
    name = models.CharField(max_length=60, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Department'

    def get_absolute_url(self):
        return reverse('department-detail',kwargs={'pk': self.id})

class GroupProfile(TemplateModel):
    group = models.OneToOneField(
        Group, 
        on_delete=models.CASCADE,
        primary_key=True,
        related_name='profile',
    )
    name = models.CharField(max_length=60, blank=True, null=True)
    menu = models.ManyToManyField(
        Menu,
        blank=True,
        symmetrical=False,
        related_name='groups'
    )

    def __str__(self):
        name_ = self.group.name
        if self.name:
            name_ = self.name
        return name_

    class Meta:
        verbose_name = 'Group Profile'

    def get_absolute_url(self):
        return reverse('groupprofile-detail',kwargs={'pk': self.pk})

templates/snippets/audit-log.html
<div class="card-footer">
<div class="accordion accordion-flush" id="accordionFlushExample">
  <div class="accordion-item">
    <h2 class="accordion-header" id="flush-headingOne">
    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
      Audit Log
    </button>
    </h2>
    <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
      <div class="accordion-body">
        <div class="row mb-3">
          <label class="col-sm-2 col-form-label">Created By:</label>
          <div class="col-sm-4">
          <input type="text" class="form-control" value="{{ object.created_by.get_full_name }}" disabled="">
          </div>
          <label class="col-sm-2 col-form-label">Date Created:</label>
          <div class="col-sm-4">
          <input type="text" class="form-control" value="{{ object.date_created }}" disabled="">
          </div>
        </div>
        <div class="row mb-3">
          <label class="col-sm-2 col-form-label">Updated By:</label>
          <div class="col-sm-4">
          <input type="text" class="form-control" value="{{ object.updated_by.get_full_name }}" disabled="">
          </div>
          <label class="col-sm-2 col-form-label">Date Updated:</label>
          <div class="col-sm-4">
          <input type="text" class="form-control" value="{{ object.date_updated }}" disabled="">
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

templates/snippets/bordered-tab-li.html
<li class="nav-item" role="presentation">
  <button class="nav-link {{ active }}" id="{{ tabId }}-tab" data-bs-toggle="tab" data-bs-target="#card-{{ tabId }}" type="button" role="tab" aria-controls="{{ tabId }}" 
  aria-selected="{% if active == 'active' %}  'true' {% else %} 'false' {% endif %}">
  {% if alt_title %} {{ alt_title|title }} {% else %} {{ tabId|title }} {% endif %}
  </button>
</li>

templates/snippets/breadcrumbs.html
<div class="pagetitle">
  <h1>{{ page_title }}</h1>
  <nav>
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'home'%}">Home</a></li>
      {% for item in parent_menu %}
          <li class="breadcrumb-item">
            <a href="{% url item.1 %}"> {{ item.0 }} </a>
          </li>
      {% endfor %}
      {% if object %}
        <li class="breadcrumb-item active">{{ object }}</li>
      {% else %}  
        <li class="breadcrumb-item active">{{ page_name }}</li>
      {% endif %}
    </ol>
  </nav>
</div><!-- End Page Title -->

templates/snippets/footer.html
  <!-- ======= Footer ======= -->
  <footer id="footer" class="footer">
    <div class="copyright">
      &copy; Copyright <strong><span>NiceAdmin</span></strong>. All Rights Reserved
    </div>
    <div class="credits">
      <!-- All the links in the footer should remain intact. -->
      <!-- You can delete the links only if you purchased the pro version. -->
      <!-- Licensing information: https://bootstrapmade.com/license/ -->
      <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/ -->
      Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

templates/snippets/form-errors.html
<div class="card-body">
{% if form.errors %}
  {% for field in form %}
    {% for error in field.errors %}
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        {{ error }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% endfor %}
  {% endfor %}
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      {{ error }}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  {% endfor %}
{% endif %}
</div>

templates/snippets/form-messages.html
{% if messages %}
  {% for message in messages %}
    <div class="alert {% if message.tags == 'error' %} alert-danger bg-danger {% else %} alert-success bg-success {% endif %} text-light border-0 alert-dismissible fade show" role="alert">
    <ul class="list-unstyled">
    <li class="{{ message.tags }}"><i class="bi bi-exclamation-circle-fill"></i> 
       {{ message }} </li>
    </ul>
    <button type="button" class="btn-close btn-close-white" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  {% endfor %}
{% endif %}

templates/snippets/header_left.html
{% load static %}

<!-- ======= Header ======= -->
  <div class="d-flex align-items-center justify-content-between">
    <a href="{% url 'home'%}" class="logo d-flex align-items-center">
      <img src="{% static 'img/xlogo.png'%}" alt=""> 
      <span class="d-none d-lg-block">DELTA</span>
    </a>
    <i class="bi bi-list toggle-sidebar-btn"></i>
    {% comment %}
    <form class="search-form d-flex align-items-center" method="POST" action="#">
      {% csrf_token %}
      <input type="text" name="query" placeholder="Search" title="Enter search keyword">
      <button type="submit" title="Search"><i class="bi bi-search"></i></button>
    </form>
    {% endcomment %}
  </div><!-- End Search Bar -->

  <nav class="header-nav ms-auto">
    <ul class="d-flex align-items-center">
      <li class="nav-item d-block d-lg-none">
        <a class="nav-link nav-icon search-bar-toggle " href="#">
          <i class="bi bi-search"></i>
        </a>
      </li>
      <!-- End Search Icon-->
      

templates/snippets/header_right.html
{% load static %}

<!-- ======= Header ======= -->
      <li class="nav-item dropdown">
        <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
          <i class="bi bi-bell"></i>
          {% if notifs.get_all_unread %}
          <span class="badge bg-primary badge-number">{{ notifs.get_all_unread.count }}</span>
          {% endif %}
        </a>
        <!-- End Notification Icon -->

        <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow notifications">
          <li class="dropdown-header">
            You have {{ notifs.get_all_unread.count }} new notifications
            {% if notifs.get_all_unread %}
            <a href="#"><span class="badge rounded-pill bg-primary p-2 ms-2">View all</span></a>
            {% endif %}
          </li>
          <li><hr class="dropdown-divider"></li>
          {% for notif in notifs.get_all_unread %}
            <li class="notification-item">
              <i class="{{ notif.get_notif_type_display }}"></i>
              <div>
                <h4>{{ notif.subject }}</h4>
                <p>{{ notif.message | truncatewords:7 }}</p>
                <p>{{ notif.created_on | timesince }} ago</p>
              </div>
            </li>
            <li><hr class="dropdown-divider"></li>
          {% endfor %}

          <li class="dropdown-footer"><a href="">Show all notifications</a></li>
        </ul><!-- End Notification Dropdown Items -->

        </li><!-- End Notification Nav -->

        <li class="nav-item dropdown">

          <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
            <i class="bi bi-chat-left-text"></i>

            {% if received_messages.get_all_unread %}
            <span class="badge bg-success badge-number">
              {{ received_messages.get_all_unread.count }}
            </span>
            {% endif %}
          </a><!-- End Messages Icon -->



          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow messages">
            <li class="dropdown-header">
              You have {{ received_messages.get_all_unread.count }} new messages
              <a href="#"><span class="badge rounded-pill bg-primary p-2 ms-2">View all</span></a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>
            {% for message in received_messages.get_all_unread %}
            <li class="message-item">
              <a href="#">
                {% if message.sender.userprofile.image_file %}
                <img src="{{ message.sender.userprofile.image_file.url }}" alt="" class="rounded-circle">
                {% else %}
                <img src="{% static 'img/logo.png'%}" alt="" class="rounded-circle">
                {% endif %}
                <div>
                  <h4>{{ message.sender.get_full_name}}</h4>
                  <p>{{ message.message|truncatewords:7}}</p>
                  <p>{{ message.date_sent|timesince }} ago</p>
                </div>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>
            {% endfor %}

            <li><hr class="dropdown-divider"></li>

            <li class="dropdown-footer"><a href="">Show all messages</a></li>
          </ul><!-- End Messages Dropdown Items -->
        </li><!-- End Messages Nav -->
        <li class="nav-item dropdown pe-3">
          

        <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
          {% if user.profile.image_file %}
          <img src="{{ user.profile.image_file.url }}" alt="Profile" class="rounded-circle">
          {% else %}
          <img src="{% static 'img/logo.png'%}" alt="Profile" class="rounded-circle">
          {% endif %}
          <span class="d-none d-md-block dropdown-toggle ps-2">{{ user.get_full_name }}</span>
        </a><!-- End Profile Image Icon -->

        <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
          <li class="dropdown-header">
            <h6>{{ user.get_full_name|title }}</h6>
            <span>{{ user.profile.job}}</span>
          </li>
          <li><hr class="dropdown-divider"></li>
          <li>
            <a class="dropdown-item d-flex align-items-center" href="{% url 'my-profile' %}">
              <i class="bi bi-person"></i><span>My Profile</span>
            </a>
          </li>
          <li><hr class="dropdown-divider"></li>
          {% if user.is_superuser %}
          <li>
            <a class="dropdown-item d-flex align-items-center" href="{% url 'admin:index'%}" target="_blank">
              <i class="bi bi-gear"></i>
              <span>Site Administration</span>
            </a>
          </li>
          <li><hr class="dropdown-divider"></li>
         {% endif %}
          
          <li>
            <a class="dropdown-item d-flex align-items-center" href="{% url 'pages-faq'%}">
              <i class="bi bi-question-circle"></i><span>Need Help?</span>
            </a>
          </li>

          <li><hr class="dropdown-divider"></li>

        
          
          <li>
            <a class="dropdown-item d-flex align-items-center" href="{% url 'logout' %}">
              <i class="bi bi-box-arrow-right"></i><span>Sign Out</span>
            </a>
          </li>
        </ul><!-- End Profile Dropdown Items -->
      </li><!-- End Profile Nav -->
    </ul>
  </nav><!-- End Icons Navigation -->

templates/snippets/navigate.html
<div class="card-footer text-center">
  <div class="btn-group" role="group" aria-label="Basic example">
    <a href="{% url 'first_record' app model %}" >
      <button type="button" class="btn btn-outline-secondary btn-sm">
       <i class="bi bi-double-chevron-left"></i> First</button>
    </a>
    <a href="{% url 'previous_record' app model object.id %}" >
      <button type="button" class="btn btn-outline-secondary btn-sm">
       <i class="bi bi-chevron-left"></i> Previous</button>
    </a>
    <a>
      <button type="button" class="btn btn-outline-secondary btn-sm disabled">
      {{ page_title|title }}: {{ object.code }}</button>
    </a>
    <a href="{% url 'next_record' app model object.id %}" >
      <button type="button" class="btn btn-outline-secondary btn-sm">
        Next <i class="bi bi-chevron-right"></i></button>
    </a>
    <a href="{% url 'last_record' app model %}" >
      <button type="button" class="btn btn-outline-secondary btn-sm">
        Last <i class="bi bi-double-chevron-right"></i></button>
    </a>
  </div>
</div>

templates/snippets/sidebar.html
{% load custom_tags %}

<!-- ======= Sidebar ======= -->
  <ul class="sidebar-nav" id="sidebar-nav">

  <li class="nav-item">
    <a class="nav-link collapsed" href="{% url 'home'%}">
      <i class="bi bi-house"></i>
      <span>Home</span>
    </a>
  </li>

  <li class="nav-heading"> 
  {% if module == 'base' %}Modules
  {% else %} {{ module }}
  {% endif %}  
  </li>
    
  {% for user_menu in user_menus %}
    {% if 'Module' in user_menu.get_menu_type_display or 'Menu' in user_menu.get_menu_type_display %} 
      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url user_menu.url_name %}">
        <i class="bi bi-{{ user_menu.icon_class }}"></i><span>{{ user_menu.name }}</span></a>
      </li>
    {% elif 'Label' in user_menu.get_menu_type_display %}
      <li class="nav-heading">{{ user_menu.name }}</li>
    {% endif %}
  {% endfor %}

  {% if user.is_superuser and module == 'base' %} 
  <li class="nav-heading"> Administrator </li>
  <li class="nav-item">
    <a class="nav-link collapsed" data-bs-target="#forms-nav" data-bs-toggle="collapse" href="#">
      <i class="bi bi-gear"></i><span>Settings</span><i class="bi bi-chevron-down ms-auto"></i>
    </a>
    <ul id="forms-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
      <li>
        <a href="{% url 'userprofile-list' %}">
        <i class="bi bi-circle"></i><span>User Profile</span>
        </a>
      </li>
      <li>
        <a href="{% url 'groupprofile-list' %}">
        <i class="bi bi-circle"></i><span>Group Profile</span>
        </a>
      </li>
      <li>
        <a href="{% url 'menu-list' %}">
        <i class="bi bi-circle"></i><span>Menu</span>
        </a>
      </li>
      {% comment %}
      <li>
        <a href="{% url 'department-list' %}">
        <i class="bi bi-circle"></i><span>Department</span>
        </a>
      </li>
      {% endcomment %}
    </ul>
  </li>

  {% endif %}
  </ul>

templates/snippets/toggle-button.html
<button id="follow-button-{{ object.id }}" class="btn btn-outline-info btn-sm" data-object-id="{{ object.id }}" data-app-name="{{ app }}" data-model-name="{{ model }}">
  {% if request.user in object.followers.all %}
    <i class="bi bi-person-dash-fill"></i> Unfollow
  {% else %}
    <i class="bi bi-person-plus-fill"></i> Follow
  {% endif %}
</button>